python-poetry/cleo

cleo/inputs/argv_input.py
tests/inputs/test_argv_input.py

I forgot to create a feature branch, but I think that nothing bad will happen :)

sys.argv should not be changed

---

README.rst
docs/introduction.rst

Resolve https://github.com/sdispater/cleo/issues/24

Update the doc according to the latest api

---

cleo/commands/command.py
tests/commands/test_command.py
tests/fixtures/no_configure_command.py
tox.ini

Makes configure() method not necessary.

---

poetry.lock
pyproject.toml

This version introduces beautiful error messages (see https://github.com/sdispater/clikit/pull/20)

Use the latest version of clikit

---

CHANGELOG.md
cleo/__init__.py
pyproject.toml

- Upgraded `clikit` to version `^0.6.0`.

Release 0.8.1

---

cleo/ui/exception_trace.py
tests/ui/test_exception_trace.py

- Fixes the highlighting of empty sources
- Fixes the rendering of docstrings

Fix issues when rendering exception traces

---

cleo/commands/command.py
docs/helpers/table.rst

Implement documented `Command.table_separator` method.

define Command.table_separator

---

.github/workflows/tests.yml
tests/commands/completion/fixtures/zsh.txt

Just trying to get CI green again

chore: enable tests to pass

---

.pre-commit-config.yaml
cleo/_utils.py
cleo/events/event_dispatcher.py
cleo/io/outputs/stream_output.py
tests/conftest.py
tests/ui/test_progress_bar.py

lint using flake8-bugbear

---

poetry.lock
pyproject.toml

- Drop dev deps specified in `.pre-commit-config.yaml` (as we've done elsewhere)
- Bump remaining dev deps
~Needs #144~

chore: upgrade deps

---

docs/conf.py

See
https://www.sphinx-doc.org/en/master/extdev/appapi.html#sphinx.application.Sphinx.add_css_file
https://github.com/sphinx-doc/sphinx/issues/7747
Fixes #105

Use add_css_file instead of add_stylesheet

---

cleo/_utils.py
cleo/commands/command.py
cleo/commands/completions_command.py
cleo/io/inputs/token_parser.py
cleo/io/outputs/section_output.py
cleo/testers/application_tester.py
cleo/testers/command_tester.py

Done with [`com2ann`](https://github.com/ilevkivskyi/com2ann)

chore: convert type comments to annotations

---

.flake8
.pre-commit-config.yaml
cleo/_utils.py
cleo/application.py
cleo/color.py
cleo/commands/base_command.py
cleo/commands/completions_command.py
cleo/descriptors/text_descriptor.py
cleo/io/inputs/argument.py
cleo/io/inputs/argv_input.py
cleo/io/inputs/definition.py
cleo/io/inputs/input.py
cleo/io/outputs/stream_output.py
cleo/terminal.py
cleo/ui/choice_question.py
cleo/ui/confirmation_question.py
cleo/ui/exception_trace.py
cleo/ui/progress_bar.py
cleo/ui/progress_indicator.py
cleo/ui/question.py
cleo/ui/table_cell_style.py
tests/formatters/test_formatter.py
tests/test_application.py
tests/test_parser.py
tests/ui/test_exception_trace.py

Added more `pre-commit` flake8 checks and fixed all errors.

Sync flake8 config with Poetry and fix problems

---

cleo/__init__.py
pyproject.toml

Bumping project version to `b1`

Fix project version

---

cleo/io/outputs/stream_output.py

This uses a check that mypy understands

chore: update windows check for mypy

---

poetry.lock
pyproject.toml

Bumping `crashtest`, which now has a `py.typed` (thanks @Secrus :partying_face:)

chore(deps): bump crashtest

---

.github/workflows/tests.yml

Copied from Poetry CI setup, PR#6618, PR#6586.
Co-authored-by: Mathieu Kniewallner <mathieu.kniewallner@gmail.com>

fix: apply pip patch and timeout function to fix macos CI jobs

---

pyproject.toml

@neersighted @branchvincent please confirm you are ok with being listed as maintainers.

Add maintainers list to pyproject.toml

---

.pre-commit-config.yaml

Housekeeping, dependencies update.

chore(pre-commit): update flake8 plugins

---

poetry.lock
pyproject.toml
tox.ini

Tox was pretty much unused, so I decided to drop it from the repo.

removal(tox): remove unused tox

---

poetry.lock

Pre-release dependency update.

Recreate lock

---

src/cleo/ui/table.py

Change regex string to less permissive one

---

CHANGELOG.md
pyproject.toml
src/cleo/__init__.py

Relax poetry-core version and prepare for 2.0.1 release

---

pyproject.toml

build: include tests in sdist

---

news/402.misc.md
src/cleo/io/outputs/stream_output.py

This PR fixes one more encoding error mentioned by @radoering in #398. I chose to change the logic based on Python version.

Fix additional encoding error

---

pyproject.toml
src/cleo/__init__.py

Overdue dev task, an update of the version to the next one.

Update version after release

---

.github/workflows/tests.yml
news/439.feat.md
news/439.removal.md
poetry.lock
pyproject.toml
src/cleo/commands/command.py
src/cleo/descriptors/text_descriptor.py
src/cleo/events/event_dispatcher.py
src/cleo/io/inputs/definition.py
src/cleo/io/io.py
src/cleo/io/outputs/null_output.py
src/cleo/io/outputs/output.py
src/cleo/loaders/factory_command_loader.py
src/cleo/ui/exception_trace/frame_collection.py
src/cleo/ui/progress_bar.py
src/cleo/ui/progress_indicator.py
src/cleo/ui/question.py
src/cleo/ui/table.py
tests/conftest.py
tests/io/inputs/test_argv_input.py
tests/ui/test_progress_bar.py
tests/ui/test_progress_indicator.py

Drop support for Python 3.8, add Python 3.13 to CI.

Drop support for Python 3.8

---

.github/workflows/downstream.yml

Add downstream testing of compatibility with Poetry

---

.github/workflows/downstream.yaml
.github/workflows/news.yaml
.github/workflows/release.yaml
.github/workflows/tests.yaml
.pre-commit-config.yaml

ci: add zizmor pre-commit hook and fix issues

---

.github/workflows/news.yaml

Fixes pipelines (for example #540)

Use latest OS for news pipeline
