cleo/formatters/output_formatter_style.py, cleo/inputs/input_definition.py
collections.OrderedDict was added in python 2.7.
This PR allows to use the backport for Python 2.6 : 
https://pypi.python.org/pypi/ordereddict
=> Use OrderedDict backport in case of Python2.6 or earlier

CHANGELOG.md, cleo/__init__.py, pyproject.toml
- Errors are now rendered in a nicer way for Python 3.6+.
=> Release 0.8.0

cleo/application.py, tests/testers/test_application_tester.py
`sys.argv` was always used even if the input was a `StringInput` instance.
This PR fixes the issue by retrieving the input's tokens instead.
=> Fix argv input reconstruction for namespace commands

cleo/commands/completions/templates.py
Prior to this change, zsh completion would break if either 'coms' or 'opts' were defined elsewhere globally.
Fixes #85
=> Declare 'coms' and 'opts' as local in zsh completion template

cleo/ui/table.py, tests/ui/test_table.py
Spooky action at a distance was possible, thanks to each table style
serving as a global singleton. To resolve this, we return a copy every
time the user modifies the style.
A regression test is included. While it does not explicitly cover more
complex cases like altering the preset, asking for another, and then
asking for the original (which should be unaltered), it should suffice
to guard against this behavior.
=> fix: table style side effects

cleo/ui/choice_question.py, cleo/ui/question.py, tests/ui/test_choice_question.py
Otherwise, an AttributeError is raised.
Related downstream ticket https://github.com/python-poetry/poetry/issues/2355.
=> Allow for empty answer in ChoiceQuestion

.pre-commit-config.yaml, docs/conf.py, poetry.lock, pyproject.toml
This fixes CI failure caused by https://github.com/pallets/click/issues/2225
=> Fix CI | Update black version in pre-commit

.pre-commit-config.yaml, pyproject.toml
mypy returns whole heap of errors in this repo. this PR sets up an incremental adoption strategy for introducing typing/mypy linting.
Every file that currently produces errors is whitelisted. Over time, this whitelist should be reduced, and eventually removed entirely.
(this is the same strategy being used in `poetry` and `poetry-core`)
=> set up mypy hook for incremental adoption

.flake8
the ignore section doesn't appear to be necessary, and many entries are in the default exclude list.
W503 is already in the default ignore list
=> Simplify flake8 config

docs/installation.rst
This rst document was using markdown syntax.
=> Fixed URL syntax in installation.rst

README.rst
Worked for me. I learned about this from poetry's README:
https://github.com/python-poetry/poetry#enable-tab-completion-for-bash-fish-or-zsh
TODO: looks like https://github.com/sdispater/cleo/blob/master/docs/introduction.rst should be aligned with this
=> Document autocompletion for brew-installed Zsh

.github/workflows/tests.yml, poetry.lock, pyproject.toml
Dropping support for EOL python3.6, which is in line with the rest of our repos
Note, I'll leave all `pyupgrade` changes to #119
=> chore: drop 3.6 support

README.md, docs/introduction.rst
Aligning this section in the doc site to match with the root README. This is a follow-up for https://github.com/python-poetry/cleo/pull/77 where the README was updated.
=> Docs: Update Autocompletion section

cleo/commands/command.py
CI [failed on master](https://github.com/python-poetry/cleo/runs/6661323193?check_suite_focus=true). Really not sure how this passed in the PR
=> chore: fix failing lint

cleo/application.py, tests/commands/test_command.py, tests/fixtures/foo3_command.py, tests/fixtures/foo_sub_namespaced3_command.py, tests/test_application.py
There are some cases where `io.input` is recreated, but the `input.stream` attribute is not properly copied over. This fixes an [upstream edge case issue in Poetry](https://github.com/python-poetry/poetry/issues/5633).
=> fix: input.stream is null when copied for namespaced commands

cleo/application.py, cleo/ui/exception_trace.py, tests/ui/test_exception_trace.py
This shifts error verbosity to reduce terminal output pollution
https://github.com/python-poetry/poetry/pull/2915
https://github.com/python-poetry/poetry/pull/5559
https://github.com/python-poetry/poetry/issues/2854
https://github.com/python-poetry/poetry/issues/3273
https://github.com/python-poetry/poetry/issues/4014
https://github.com/python-poetry/poetry/issues/5229
- **default**: render error with source reference and solution if present
- `CleoSimpleException`: render it with just a message, never display solution
- `io.is_verbose()`: **default** + full stack trace 
- **default** / `CleoSimpleException`: render error with just a message + solution if present
- `io.is_verbose()`: render error with source reference + solution if present
- `io.is_very_verbose()`: `io.is_verbose()` + …
=> Decrease default errors verbosity

.pre-commit-config.yaml, tests/fixtures/exceptions/nested1.py, tests/fixtures/exceptions/nested2.py, tests/fixtures/exceptions/recursion.py, tests/fixtures/exceptions/simple.py, tests/fixtures/exceptions/solution.py, tests/ui/helpers.py, tests/ui/test_exception_trace.py
Currently, `test_exception_trace.py` tests exact line numbers in stack traces of code within its own file. This makes it hard for refactoring, so instead factor as much out into separate fixture files.
=> refactor: move exception fixtures out tests

.github/workflows/tests.yml
Start testing against Python 3.11.
Also update workflows so that tests only run on pull requests and the main branch for branches builds, set default shell to avoid duplication and bump `actions/cache`.
=> Test against Python 3.11

.github/workflows/tests.yml, .pre-commit-config.yaml
now handled by `pre-commit.ci`
=> ci: drop lint from github actions

cleo/io/outputs/stream_output.py
Fixes https://github.com/python-poetry/poetry/issues/3602
Not clear to me what the intention of all that flushing was, I haven't seen any obvious downside to getting rid of it altogether.
=> don't flush() on every write()

.github/workflows/tests.yml
Python 3.11 CI setup is flaky and constantly fails. For maintainers' peace of mind, it's being removed in this PR.
=> Remove python 3.11 from CI

cleo/_utils.py, poetry.lock, pyproject.toml, tests/test_utils.py
on most platforms this improves the performance by 30-40x by using a highly optimized C extension.
On unsupported platforms falls back to a pure Python implementation, which still improves performance by 2x.
I am not really familiar with poetry. I used:
```bash
poetry add rapidfuzz
poetry remove pylev
```
However this removed files for a lot of dependencies, which seems wrong. What is the correct process to replace a dependency?
=> improve performance of find_similar_names

.github/workflows/tests.yml
Since macOS doesn't come with a `timeout` command, our venv health check fails and removes our venv each time (for example, see [the logs](https://github.com/python-poetry/cleo/runs/7549937631?check_suite_focus=true#step:10:7)). I've skipped the healthcheck here since I'm not sure how often it's really needed, but if we find it is we should find a cross-platform solution.
=> ci: fix cache on macOS

README.md, docs/introduction.rst
Found the style got changed in [formatter](https://github.com/python-poetry/cleo/blob/db6f7957a00383df097386a23309f4787ef3faff/cleo/formatters/formatter.py#L22-L28) but the document isn't updated.
Feeling a bit misleading so fix it.
=> Fix document of text coloring

cleo/commands/completions/templates.py, tests/commands/completion/fixtures/zsh.txt
Before we were implicitly declaring the `opts` and `coms` arrays, which had the undesired effect of zsh parsing it as an associative array instead of a normal array. 
Now we explicitly declare the `opts` and `coms` arrays to be normal arrays.
=> Fix zsh completion

cleo/application.py, tests/fixtures/foo3_command.py, tests/fixtures/foo_sub_namespaced3_command.py, tests/test_application.py
When running a namespaced command like `cache clear`, we reset the input (seemingly to parse the command as a single string) but also unintentionally reset `io.input._interactive`.
Similar bug as #135
Relates to https://github.com/python-poetry/poetry/pull/6212
=> fix: don't clear `interactive` state on namespace commands

cleo/io/outputs/stream_output.py
Follow up to #228, `supports_utf8` must be a function (not sure why mypy didn't catch this):
https://github.com/python-poetry/cleo/blob/1f7e94a55881e03c3d9ebf563134885c468f0988/cleo/io/outputs/output.py#L61-L65
=> fix: `Output.supports_utf8` must be a function

.pre-commit-config.yaml, pyproject.toml
- moved all possible configs from `.pre-commit-config.yaml` to `pyproject.toml`
- revied all config options 
- updated `additional_dependencies` for `yesqa` and `flake8` pre-commit hooks
- reordered pre-commit hooks for in a way it makes more sense (like removing imports before formatting or linter checks)
=> chore(config): cleanup configs

cleo/ui/question.py
Related to python-poetry/poetry#2356. 
I have tested this manually with an example from the original issue.
=> fix(question): restore terminal settings on ^C

cleo/application.py, cleo/io/inputs/input.py, cleo/testers/application_tester.py
This infers `--no-interaction` when stdin is [not a TTY](https://docs.python.org/3/library/io.html#io.IOBase.isatty)
Before:
```console
$ : | poetry cache clear --all .
Delete 615 entries? (yes/no) [no]
Aborted
```
After:
```console
$ : | poetry cache clear --all .
```
Fixes #232
=> feat: set `--no-interaction` when stdin is not a tty

cleo/application.py, cleo/io/outputs/stream_output.py
When fixing #234, I noticed cleo's terminal prompt wasn't rendering until after reading a response:
```console
$ poetry cache clear --all .
no # cleo is prompting here
Delete 575 entries? (yes/no) [no] # but output is displayed later
```
This was introduced via #165, since now we aren't always flushing the output. This reverts that and instead suppresses a broken pipe error, which was the initial motivation for that PR.
Note that `click` also [always flushes output](https://github.com/pallets/click/blob/08f71b08e2b7ee9b1ea27daf6d3040999fc68551/src/click/utils.py#L225) and similary [ignores broken pipes](https://github.com/pallets/click/blob/08f71b08e2b7ee9b1ea27daf6d3040999fc68551/src/click/utils.py#L452).
I manually tested this with `poetry -V | head -1`
Closes #56
=> fix: gracefully handle SIGPIPE

.github/workflows/tests.yml, CHANGELOG.md
=> chore: rename default branch to `main`

.github/workflows/release.yml, .github/workflows/tests.yml
`set-output` is now deprecated.
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/ shows the new way of exporting outputs.
Also changed the formatting in the release action and renamed the steps to be more verbose.
=> Use env vars for exporting output

poetry.lock, pyproject.toml
Bumping `mypy` to the latest version. Also dropping one config option since it's now a default.
=> chore(mypy): bump mypy version

src/cleo/application.py, src/cleo/color.py, src/cleo/commands/base_command.py, src/cleo/descriptors/application_description.py, src/cleo/events/console_error_event.py, src/cleo/exceptions/__init__.py, src/cleo/formatters/formatter.py, src/cleo/formatters/style_stack.py, src/cleo/io/inputs/argument.py, src/cleo/io/inputs/argv_input.py, src/cleo/io/inputs/definition.py, src/cleo/io/inputs/input.py, src/cleo/io/inputs/option.py, src/cleo/loaders/factory_command_loader.py, src/cleo/ui/choice_question.py, src/cleo/ui/ui.py, tests/io/inputs/test_argument.py, tests/io/inputs/test_option.py, tests/loaders/test_factory_command_loader.py, tests/test_application.py, tests/ui/test_choice_question.py
=> Rename custom exceptions form *Exception to *Error 

src/cleo/commands/completions_command.py, tests/commands/completion/fixtures/bash.txt, tests/commands/completion/fixtures/command_with_space_in_name.py, tests/commands/completion/fixtures/fish.txt, tests/commands/completion/fixtures/zsh.txt
This P.R tries to fix the behavior described in [poetry's Fish completions raise errors but still works](https://github.com/python-poetry/poetry/issues/5929#issuecomment-1345580021) issue.
I'm running
```
❯ pip freeze |grep -E 'poetry|cleo'
cleo==2.0.1
poetry==1.3.1
poetry-core==1.4.0
poetry-plugin-export==1.2.0
```
```
❯ python -V
Python 3.10.6
```
A `--goodbye` option was added to the `spaced command` in the `cleo` test suite. Adding this option mimics the problem described in [poetry's Fish completions raise errors but still works](https://github.com/python-poetry/poetry/issues/5929#issuecomment-1345580021) issue.
`fish` shell fixture was modified to what I consider a valid solution to the problem.
Generated `fish` completion file before and after the patch:
**before the patch**
``` …
```
=> Sanitize command name in fish shell generated completion file

docs/introduction.rst
The existing examples result in an `ImportError`.
=> Fix CommandTester imports in the documentation

.flake8, .pre-commit-config.yaml, pyproject.toml
Gradual migration to a `ruff` linter. The flake8 plugins that don't have counterparts in `ruff` are still checked by flake8 until they are not implemented.
=> Implement ruff checks

.pre-commit-config.yaml, pyproject.toml
Replaces `pyupgrade`, `pycln`, and `isort` with `ruff` (same as https://github.com/python-poetry/poetry/pull/7850)
Config was also copied from poetry
=> chore: expand ruff usage

news/299.bugfix.md, src/cleo/application.py, src/cleo/io/outputs/section_output.py, src/cleo/terminal.py, src/cleo/ui/progress_bar.py, tests/test_terminal.py
Closes: python-poetry/poetry#7184
This fixes the issue, where in Python <3.11 `shutil.get_terminal_size()` would return `(0, 0)` size in non-TTY terminals.
=> Fix terminal size detection

news/313.bugfix.md, src/cleo/io/outputs/stream_output.py
Credit to @TBBle for this fix in #104
- resolves #104
- resolves https://github.com/python-poetry/poetry/issues/1972
- resolves https://github.com/python-poetry/poetry/issues/3354
Poetry output before and after this change:
=> (🐞) stream_output: correctly handle virtual terminal ANSI support

news/344.misc.md, src/cleo/color.py, src/cleo/commands/command.py, src/cleo/commands/completions_command.py, src/cleo/descriptors/text_descriptor.py, src/cleo/formatters/formatter.py, src/cleo/ui/choice_question.py, src/cleo/ui/confirmation_question.py, src/cleo/ui/exception_trace.py, src/cleo/ui/table_cell_style.py, tests/ui/test_confirmation_question.py, tests/ui/test_exception_trace.py
- Made f-strings use outer double quotes when doing interpolation (probably ignored by a formatter), e.g.
```diff
-f' It must be one of {", ".join(self.COLORS.keys())}'
+f" It must be one of {', '.join(self.COLORS.keys())}"
```
- Flipped quotes for a raw string using both inside:
```diff
-r'a\'"z'
+r"a'\"z"
```
- Made all RegEx strings raw strings, e.g.
```diff
-"(?i)^y"
+r"(?i)^y"
```
=> Improved string styling

.github/workflows/tests.yml, tests/conftest.py, tests/ui/test_progress_bar.py, tests/ui/test_progress_indicator.py
We had a few `time.sleep`'s to test advancing progress bars, but really slowed down our tests. This mocks `time.now` instead, reducing the test suite (on my machine) from ~5s to ~0.5s.
=> test: speed up test suite

.github/workflows/tests.yml, pyproject.toml
This has two ci simplifications:
- Replace our manual caching with the one builtin to `actions/setup-python`, which has been supported since https://github.com/actions/setup-python/releases/tag/v3.1.0
- Use `pipx` to install poetry, which decouples poetry's required python version from ours and also doesn't require manually updating `$PATH`
=> ci: use `actions/setup-python`'s cache

src/cleo/_utils.py, src/cleo/application.py, src/cleo/commands/base_command.py, src/cleo/commands/command.py, src/cleo/commands/completions_command.py, src/cleo/descriptors/application_description.py, src/cleo/descriptors/descriptor.py, src/cleo/descriptors/text_descriptor.py, src/cleo/events/event_dispatcher.py, src/cleo/exceptions/__init__.py, src/cleo/formatters/formatter.py, src/cleo/formatters/style.py, src/cleo/formatters/style_stack.py, src/cleo/io/inputs/argv_input.py, src/cleo/io/inputs/definition.py, src/cleo/io/outputs/section_output.py, src/cleo/ui/choice_question.py, src/cleo/ui/table.py, src/cleo/ui/table_cell_style.py, src/cleo/ui/table_style.py
=> Miscellaneous improvements throughout the codebase

news/357.bugfix.md, src/cleo/commands/completions_command.py, tests/commands/completion/fixtures/fish.txt
Fixes #84
Fixes #359
Fixes #231 
Fixes #366
=> fix: properly complete subcommands for fish

.github/workflows/tests.yml, news/398.misc.md, src/cleo/ui/exception_trace/frame.py, src/cleo/ui/question.py, tests/commands/completion/test_completions_command.py, tests/test_application.py, tests/ui/exception_trace/test_frame.py, tests/ui/test_question.py
This PR fixes Encoding Warnings with PEP 597 warnings enabled and enables the warnings in CI. It goes along with https://github.com/python-poetry/poetry/pull/8893 and https://github.com/python-poetry/poetry-core/pull/685.
=> Fix encoding warnings with PEP 597 enabled

news/408.feat.md, tests/test_utils.py
For some reason, `strip_tags` didn't have tests, so I added one.
=> Improve `cleo._utils` coverage

.pre-commit-config.yaml, pyproject.toml, src/cleo/ui/progress_indicator.py, tests/ui/test_progress_bar.py, tests/ui/test_progress_indicator.py
See details below for changes overview sourced from [the Ruff's changelog](https://github.com/astral-sh/ruff/blob/9675e1867a73e536a609e971f2e823c799771afc/CHANGELOG.md).
As of 08bcb3c, the update implies updates in 3 files.
The current ruff-pre-commit version runs some linter-formatter conflicting rules.
<details>
- Improve single-`with` item formatting for Python 3.8 or older ([#10276](https://github.com/astral-sh/ruff/pull/10276))
- \[`pyupgrade`\] Allow fixes for f-string rule regardless of line length (`UP032`) ([#10263](https://github.com/astral-sh/ruff/pull/10263))
- \[`pycodestyle`\] Include actual conditions in E712 diagnostics ([#10254](https://github.com/astral-sh/ruff/pull/10254))
- Fix trailing kwargs end of line comment after slash …
=> Bump ruff-pre-commit to v0.3.2

.github/workflows/tests.yml
Old `macos-12` is [deprecated](https://github.com/actions/runner-images/issues/10721).
=> Update macos image used in CI

.github/workflows/tests.yaml, news/506.feat.md
Since Python 3.14 is coming out soon, let's add it to the test matrix.
=> Add Python 3.14 to the test matrix

news/508.bugfix.md, src/cleo/ui/exception_trace/inspector.py, tests/fixtures/exceptions/raiser_with_suppressed_context.py, tests/ui/test_exception_trace.py
=> Fix `__suppress_context__` not being respected in exception rendering
